version: '3'

services:
  database:
    image: 'postgres:15-alpine'
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8081:80
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
  db-data:
